name: "Import Keystore"
on: [workflow_call]

jobs:
   import-keystore:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Release bundle
        env:
          GT_USERNAME: "BreakZero"
          GT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew Wallet-Android:app:assembleProdRelease

